bugfix - handle reserved word 'provider' (#44)
If a Fleet module contains a variable named 'provider' then
expose it as 'provider_name' in the Terraform module.

This assumes that no Fleet module use both 'provider' and 'provider_name'.

Fixes errors like

    Error: Invalid variable name

    The variable name "provider" is reserved due to its special meaning inside module blocks.