fleet-package-generator - fail if glob doesn't match
If a glob is specified that doesn't match any package then treat this as
an error. It is mostly a mistake or a change to the packages, and in either
case requires user attention.

Error: package specifier "ti_abusech/*/*/httpjson" does not match any known package